export const browserCoreExamples = [
  "marv browser status",
  "marv browser start",
  "marv browser stop",
  "marv browser tabs",
  "marv browser open https://example.com",
  "marv browser focus abcd1234",
  "marv browser close abcd1234",
  "marv browser screenshot",
  "marv browser screenshot --full-page",
  "marv browser screenshot --ref 12",
  "marv browser snapshot",
  "marv browser snapshot --format aria --limit 200",
  "marv browser snapshot --efficient",
  "marv browser snapshot --labels",
];

export const browserActionExamples = [
  "marv browser navigate https://example.com",
  "marv browser resize 1280 720",
  "marv browser click 12 --double",
  'marv browser type 23 "hello" --submit',
  "marv browser press Enter",
  "marv browser hover 44",
  "marv browser drag 10 11",
  "marv browser select 9 OptionA OptionB",
  "marv browser upload /tmp/marv/uploads/file.pdf",
  'marv browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "marv browser dialog --accept",
  'marv browser wait --text "Done"',
  "marv browser evaluate --fn '(el) => el.textContent' --ref 7",
  "marv browser console --level error",
  "marv browser pdf",
];
