import fs from "node:fs/promises";
import path from "node:path";
import { type MarvConfig, loadConfig } from "../../core/config/config.js";
import { resolveMarvAgentDir } from "../agent-paths.js";
import { getBaselineModels } from "./model-baselines.js";
import { ensureMarvModelsJson } from "./models-config.js";

export type ModelCatalogEntry = {
  id: string;
  name: string;
  provider: string;
  contextWindow?: number;
  reasoning?: boolean;
  input?: Array<"text" | "image">;
};

let modelCatalogPromise: Promise<ModelCatalogEntry[]> | null = null;
let hasLoggedModelCatalogError = false;

// Test-only: pluggable loader for models.json (replaces the old Pi SDK mock).
type ModelsJsonLoader = (agentDir: string) => Promise<ModelsJsonFile | null>;
let loadModelsJsonOverride: ModelsJsonLoader | null = null;

type ModelsJsonModel = {
  id: string;
  name?: string;
  contextWindow?: number;
  reasoning?: boolean;
  input?: Array<"text" | "image">;
};

type ModelsJsonProvider = {
  baseUrl?: string;
  api?: string;
  models?: ModelsJsonModel[];
};

type ModelsJsonFile = {
  providers?: Record<string, ModelsJsonProvider>;
};

export function resetModelCatalogCacheForTest() {
  modelCatalogPromise = null;
  hasLoggedModelCatalogError = false;
  loadModelsJsonOverride = null;
}

// Test-only escape hatch: allow mocking the models.json loader.
export function __setModelCatalogImportForTest(loader?: (() => Promise<unknown>) | null) {
  // Legacy compat: old tests pass a Pi SDK module loader.
  // New tests can pass a ModelsJsonLoader. Accept both.
  if (!loader) {
    loadModelsJsonOverride = null;
    return;
  }
  loadModelsJsonOverride = async (agentDir: string) => {
    try {
      const mod = await loader();
      // If it returns something with discoverModels/discoverAuthStorage (legacy Pi SDK mock),
      // try to run it and extract models. Otherwise treat as a models.json object.
      if (mod && typeof mod === "object" && "discoverModels" in (mod as Record<string, unknown>)) {
        const piMod = mod as {
          AuthStorage: unknown;
          discoverModels: (auth: unknown, dir: string) => { getAll: () => unknown[] };
          discoverAuthStorage: (dir: string) => unknown;
        };
        const authStorage = piMod.discoverAuthStorage(agentDir);
        const registry = piMod.discoverModels(authStorage, agentDir);
        const entries = Array.isArray(registry) ? registry : registry.getAll();
        return {
          providers: {
            _legacy: {
              models: (entries as Array<Record<string, unknown>>).map((e) => ({
                id: String((e.id as string) ?? ""),
                name: String((e.name as string) ?? (e.id as string) ?? ""),
                provider: String((e.provider as string) ?? ""),
                contextWindow: typeof e.contextWindow === "number" ? e.contextWindow : undefined,
                reasoning: typeof e.reasoning === "boolean" ? e.reasoning : undefined,
                input: Array.isArray(e.input) ? e.input : undefined,
              })),
            },
          },
        } as ModelsJsonFile;
      }
      return mod as ModelsJsonFile;
    } catch {
      return null;
    }
  };
}

/**
 * Read the models.json file from the agent directory.
 * This file is generated by ensureMarvModelsJson() and contains
 * user-configured providers with their models.
 */
async function readModelsJson(agentDir: string): Promise<ModelsJsonFile | null> {
  if (loadModelsJsonOverride) {
    return loadModelsJsonOverride(agentDir);
  }
  try {
    const filePath = path.join(agentDir, "models.json");
    const raw = await fs.readFile(filePath, "utf8");
    return JSON.parse(raw) as ModelsJsonFile;
  } catch {
    return null;
  }
}

/**
 * Extract ModelCatalogEntry[] from a models.json file.
 * Each provider key in the file becomes the provider name,
 * and each model entry under it becomes a catalog entry.
 */
function extractModelsFromJson(json: ModelsJsonFile): ModelCatalogEntry[] {
  const models: ModelCatalogEntry[] = [];
  if (!json.providers) {
    return models;
  }
  for (const [providerId, provider] of Object.entries(json.providers)) {
    if (!provider?.models?.length) {
      continue;
    }
    for (const model of provider.models) {
      const id = String(model.id ?? "").trim();
      if (!id) {
        continue;
      }
      // Legacy compat: if the model has a provider field (from test mocks), use it.
      const providerName =
        (model as Record<string, unknown>).provider &&
        typeof (model as Record<string, unknown>).provider === "string"
          ? String((model as Record<string, unknown>).provider)
          : providerId;
      models.push({
        id,
        name: String(model.name ?? id).trim() || id,
        provider: providerName,
        contextWindow:
          typeof model.contextWindow === "number" && model.contextWindow > 0
            ? model.contextWindow
            : undefined,
        reasoning: typeof model.reasoning === "boolean" ? model.reasoning : undefined,
        input: Array.isArray(model.input) ? model.input : undefined,
      });
    }
  }
  return models;
}

const sortModels = (entries: ModelCatalogEntry[]) =>
  entries.sort((a, b) => {
    const p = a.provider.localeCompare(b.provider);
    if (p !== 0) {
      return p;
    }
    return a.name.localeCompare(b.name);
  });

/**
 * Load the model catalog by merging:
 * 1. Hardcoded baselines (model-baselines.ts) — always available
 * 2. User-configured models from models.json — custom/local providers
 *
 * Runtime Registry API-fetch later enhances this with live provider data.
 */
export async function loadModelCatalog(params?: {
  config?: MarvConfig;
  useCache?: boolean;
}): Promise<ModelCatalogEntry[]> {
  if (params?.useCache === false) {
    modelCatalogPromise = null;
  }
  if (modelCatalogPromise) {
    return modelCatalogPromise;
  }

  modelCatalogPromise = (async () => {
    try {
      const cfg = params?.config ?? loadConfig();
      await ensureMarvModelsJson(cfg);

      const agentDir = resolveMarvAgentDir();

      // Start with hardcoded baselines for known providers.
      const baselines = getBaselineModels();
      const seen = new Set(baselines.map((m) => `${m.provider}/${m.id}`));

      // Read user-configured models from models.json and merge.
      const json = await readModelsJson(agentDir);
      const configured = json ? extractModelsFromJson(json) : [];
      for (const entry of configured) {
        const key = `${entry.provider}/${entry.id}`;
        if (!seen.has(key)) {
          baselines.push(entry);
          seen.add(key);
        }
      }

      if (baselines.length === 0) {
        modelCatalogPromise = null;
      }

      return sortModels(baselines);
    } catch (error) {
      if (!hasLoggedModelCatalogError) {
        hasLoggedModelCatalogError = true;
        console.warn(`[model-catalog] Failed to load model catalog: ${String(error)}`);
      }
      modelCatalogPromise = null;
      // Fall back to baselines only.
      return sortModels(getBaselineModels());
    }
  })();

  return modelCatalogPromise;
}

/**
 * Check if a model supports image input based on its catalog entry.
 */
export function modelSupportsVision(entry: ModelCatalogEntry | undefined): boolean {
  return entry?.input?.includes("image") ?? false;
}

/**
 * Find a model in the catalog by provider and model ID.
 */
export function findModelInCatalog(
  catalog: ModelCatalogEntry[],
  provider: string,
  modelId: string,
): ModelCatalogEntry | undefined {
  const normalizedProvider = provider.toLowerCase().trim();
  const normalizedModelId = modelId.toLowerCase().trim();
  return catalog.find(
    (entry) =>
      entry.provider.toLowerCase() === normalizedProvider &&
      entry.id.toLowerCase() === normalizedModelId,
  );
}
