#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS_DIR="${ROOT_DIR}/apps/ios"
TEAM_ID_SCRIPT="${ROOT_DIR}/scripts/ios-team-id.sh"
LOCAL_SIGNING_FILE="${IOS_DIR}/.local-signing.xcconfig"

sanitize_bundle_id() {
  local raw="${1:-}"
  raw="$(printf '%s' "$raw" | tr '[:upper:]' '[:lower:]')"
  raw="$(printf '%s' "$raw" | sed -E 's/[^a-z0-9.-]+/-/g; s/\.+/./g; s/^-+//; s/[.-]+$//')"
  if [[ -z "$raw" ]]; then
    raw="ai.marv.ios.test.local"
  fi
  printf '%s\n' "$raw"
}

if [[ ! -x "${TEAM_ID_SCRIPT}" ]]; then
  echo "ERROR: Missing team detection helper: ${TEAM_ID_SCRIPT}" >&2
  exit 1
fi

team_id="$("${TEAM_ID_SCRIPT}")"
bundle_id="$(sanitize_bundle_id "${MARV_IOS_APP_BUNDLE_ID:-ai.marv.ios.test.local}")"
code_sign_style="${MARV_IOS_CODE_SIGN_STYLE:-Automatic}"
app_profile="${MARV_IOS_APP_PROFILE:-}"

tmp_file="$(mktemp "${TMPDIR:-/tmp}/marv-ios-signing.XXXXXX")"
cat >"${tmp_file}" <<EOF
// Auto-generated by scripts/ios-configure-signing.sh.
// This file is local-only and should not be committed.
MARV_IOS_CODE_SIGN_STYLE = ${code_sign_style}
MARV_IOS_DEVELOPMENT_TEAM = ${team_id}
MARV_IOS_APP_BUNDLE_ID = ${bundle_id}
MARV_IOS_APP_PROFILE = ${app_profile}
EOF

if [[ -f "${LOCAL_SIGNING_FILE}" ]] && cmp -s "${tmp_file}" "${LOCAL_SIGNING_FILE}"; then
  rm -f "${tmp_file}"
  echo "iOS signing config already up to date: team=${team_id} app=${bundle_id}"
  exit 0
fi

mv "${tmp_file}" "${LOCAL_SIGNING_FILE}"
echo "Configured iOS signing: team=${team_id} app=${bundle_id}"
